[package]
name = "mcp2221"
version = "0.1.0"
authors = ["Patrick O'Doherty <p@trickod.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hidapi = "0.1.5"